### YamlMime:ManagedReference
items:
- uid: Mixture.OutputTextureSettings.Preset
  commentId: T:Mixture.OutputTextureSettings.Preset
  id: OutputTextureSettings.Preset
  parent: Mixture
  children:
  - Mixture.OutputTextureSettings.Preset.Color
  - Mixture.OutputTextureSettings.Preset.DetailHDRP
  - Mixture.OutputTextureSettings.Preset.DetailURP
  - Mixture.OutputTextureSettings.Preset.Height
  - Mixture.OutputTextureSettings.Preset.MaskHDRP
  - Mixture.OutputTextureSettings.Preset.Normal
  - Mixture.OutputTextureSettings.Preset.Raw
  langs:
  - csharp
  - vb
  name: OutputTextureSettings.Preset
  nameWithType: OutputTextureSettings.Preset
  fullName: Mixture.OutputTextureSettings.Preset
  type: Enum
  source:
    remote:
      path: Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
      branch: master
      repo: git@github.com:alelievr/Mixture.git
    id: Preset
    path: ../../Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
    startLine: 51
  assemblies:
  - Mixture.Runtime
  namespace: Mixture
  syntax:
    content: public enum Preset
    content.vb: Public Enum Preset
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Mixture.OutputTextureSettings.Preset.Color
  commentId: F:Mixture.OutputTextureSettings.Preset.Color
  id: Color
  parent: Mixture.OutputTextureSettings.Preset
  langs:
  - csharp
  - vb
  name: Color
  nameWithType: OutputTextureSettings.Preset.Color
  fullName: Mixture.OutputTextureSettings.Preset.Color
  type: Field
  source:
    remote:
      path: Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
      branch: master
      repo: git@github.com:alelievr/Mixture.git
    id: Color
    path: ../../Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
    startLine: 53
  assemblies:
  - Mixture.Runtime
  namespace: Mixture
  syntax:
    content: Color = 0
    return:
      type: Mixture.OutputTextureSettings.Preset
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mixture.OutputTextureSettings.Preset.Raw
  commentId: F:Mixture.OutputTextureSettings.Preset.Raw
  id: Raw
  parent: Mixture.OutputTextureSettings.Preset
  langs:
  - csharp
  - vb
  name: Raw
  nameWithType: OutputTextureSettings.Preset.Raw
  fullName: Mixture.OutputTextureSettings.Preset.Raw
  type: Field
  source:
    remote:
      path: Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
      branch: master
      repo: git@github.com:alelievr/Mixture.git
    id: Raw
    path: ../../Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
    startLine: 54
  assemblies:
  - Mixture.Runtime
  namespace: Mixture
  syntax:
    content: Raw = 1
    return:
      type: Mixture.OutputTextureSettings.Preset
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mixture.OutputTextureSettings.Preset.Normal
  commentId: F:Mixture.OutputTextureSettings.Preset.Normal
  id: Normal
  parent: Mixture.OutputTextureSettings.Preset
  langs:
  - csharp
  - vb
  name: Normal
  nameWithType: OutputTextureSettings.Preset.Normal
  fullName: Mixture.OutputTextureSettings.Preset.Normal
  type: Field
  source:
    remote:
      path: Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
      branch: master
      repo: git@github.com:alelievr/Mixture.git
    id: Normal
    path: ../../Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
    startLine: 55
  assemblies:
  - Mixture.Runtime
  namespace: Mixture
  syntax:
    content: Normal = 2
    return:
      type: Mixture.OutputTextureSettings.Preset
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mixture.OutputTextureSettings.Preset.Height
  commentId: F:Mixture.OutputTextureSettings.Preset.Height
  id: Height
  parent: Mixture.OutputTextureSettings.Preset
  langs:
  - csharp
  - vb
  name: Height
  nameWithType: OutputTextureSettings.Preset.Height
  fullName: Mixture.OutputTextureSettings.Preset.Height
  type: Field
  source:
    remote:
      path: Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
      branch: master
      repo: git@github.com:alelievr/Mixture.git
    id: Height
    path: ../../Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
    startLine: 56
  assemblies:
  - Mixture.Runtime
  namespace: Mixture
  syntax:
    content: Height = 3
    return:
      type: Mixture.OutputTextureSettings.Preset
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mixture.OutputTextureSettings.Preset.MaskHDRP
  commentId: F:Mixture.OutputTextureSettings.Preset.MaskHDRP
  id: MaskHDRP
  parent: Mixture.OutputTextureSettings.Preset
  langs:
  - csharp
  - vb
  name: MaskHDRP
  nameWithType: OutputTextureSettings.Preset.MaskHDRP
  fullName: Mixture.OutputTextureSettings.Preset.MaskHDRP
  type: Field
  source:
    remote:
      path: Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
      branch: master
      repo: git@github.com:alelievr/Mixture.git
    id: MaskHDRP
    path: ../../Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
    startLine: 57
  assemblies:
  - Mixture.Runtime
  namespace: Mixture
  syntax:
    content: MaskHDRP = 4
    return:
      type: Mixture.OutputTextureSettings.Preset
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mixture.OutputTextureSettings.Preset.DetailHDRP
  commentId: F:Mixture.OutputTextureSettings.Preset.DetailHDRP
  id: DetailHDRP
  parent: Mixture.OutputTextureSettings.Preset
  langs:
  - csharp
  - vb
  name: DetailHDRP
  nameWithType: OutputTextureSettings.Preset.DetailHDRP
  fullName: Mixture.OutputTextureSettings.Preset.DetailHDRP
  type: Field
  source:
    remote:
      path: Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
      branch: master
      repo: git@github.com:alelievr/Mixture.git
    id: DetailHDRP
    path: ../../Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
    startLine: 58
  assemblies:
  - Mixture.Runtime
  namespace: Mixture
  syntax:
    content: DetailHDRP = 5
    return:
      type: Mixture.OutputTextureSettings.Preset
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Mixture.OutputTextureSettings.Preset.DetailURP
  commentId: F:Mixture.OutputTextureSettings.Preset.DetailURP
  id: DetailURP
  parent: Mixture.OutputTextureSettings.Preset
  langs:
  - csharp
  - vb
  name: DetailURP
  nameWithType: OutputTextureSettings.Preset.DetailURP
  fullName: Mixture.OutputTextureSettings.Preset.DetailURP
  type: Field
  source:
    remote:
      path: Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
      branch: master
      repo: git@github.com:alelievr/Mixture.git
    id: DetailURP
    path: ../../Packages/com.alelievr.mixture/Runtime/Nodes/OutputTextureSettings.cs
    startLine: 59
  assemblies:
  - Mixture.Runtime
  namespace: Mixture
  syntax:
    content: DetailURP = 6
    return:
      type: Mixture.OutputTextureSettings.Preset
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Mixture
  commentId: N:Mixture
  name: Mixture
  nameWithType: Mixture
  fullName: Mixture
- uid: Mixture.OutputTextureSettings.Preset
  commentId: T:Mixture.OutputTextureSettings.Preset
  parent: Mixture
  name: OutputTextureSettings.Preset
  nameWithType: OutputTextureSettings.Preset
  fullName: Mixture.OutputTextureSettings.Preset
